### ISSUE TITLE
[Question] URDF collision objects

### ISSUE THREAD

**Issue by EastskyKang** [dartsim/dart#1052]
I am using ```DartLoader``` to load my URDF file. (a quadruped robot)

I want to use primitive collision shapes for each link. For instance, the base link of my robot is defined as follow:

```xml
<link name="base">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="anymal_base_2.dae" scale="0.001 0.001     0.001"/>
            </geometry>
            <material name="anymal_material"/>
        </visual>
        <collision>
            <!-- Main Body -->
            <origin rpy="0 0 0" xyz="0 0 0.08"/>
            <geometry>
                <box size="0.531 0.232 0.26"/>
            </geometry>
        </collision>
    </link>
```

As I load URDF file by ```DartLoader```, it seems the root bodyNode (which corresponds to the base link) has two shapes, both mesh and box. Since it has only one collision node, bodyNode should have only one shape (that's what I expected.)

Is there any ways to create shapes(collision objects) which only correspond to ```<collision>``` node?

I am working on version 6.3 (stable) dart.

**Comment by mxgrey** [comment]
I assume you're using DART 6 or higher, please let us know if that's not the case.

This URDF will result in the BodyNode named "base" having two ShapeNodes attached to it

1. One of the ShapeNodes attached to "base" will correspond to the visual geometry defined by `<visual> ... </visual>`
2. The other ShapeNode attached to "base" will correspond to the collision geometry defined by `<collision> ... </collision>`

You could remove the `<visual>` element and you'd be left with only one ShapeNode, corresponding to the collision geometry, but then the "base" link will not be visible if you try to visualize the simulation.

Can you copy/paste some example code of how you're retrieving and using the ShapeNodes from "base"? That would allow me to give you some suggestions about how to tweak your code so that you're only handling the collision ShapeNodes.

**Comment by mxgrey** [comment]
In case it's helpful, you can do

```
std::vector<dart::dynamics::ShapeNode*> shapeNodes = bodyNode->getShapeNodesWith<dart::dynamics::CollisionAspect>();
```

to get a vector of a BodyNode's ShapeNodes which contain collision data.

**Comment by EastskyKang** [comment]
I just realize I can only get collision shape by 

```
body->getShapeNodesWith<dart::dynamics::CollisionAspect>
```

thank you so much for your quick response. I will close this issue.
