### ISSUE TITLE
ODE internal error

### ISSUE THREAD

**Issue by yangyanzhe** [dartsim/dart#1084]
#### Environment
DART version: 6.4.0
OS version and name: macOS Sierra

#### Description
Hi, I am running trajectory optimization but got the following ODE internal errors after tens of iterations:

ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)
ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)
ODE Message 3: LCP internal error, s <= 0 (s=-4.1688e+34)
ODE Message 3: LCP internal error, s <= 0 (s=0.0000e+00)
ODE INTERNAL ERROR 1: assertion "d[i] != dReal(0.0)" failed in _dLDLTRemove()

Why does it happen? Is there some way to help resolve it? I call world->reset() frequently so that I can get a clean end state given the start state and controls. Is calling reset() the expected way to reset simulation-related the information?

**Comment by jslee02** [comment]
The error message basically means the constraint solver was unable to solve the LCP problem successfully. There are several possible causes for this, which is not easy to pinpoint it given information. But calling `reset()` shouldn't be the direct reason for this.

> Is calling reset() the expected way to reset simulation-related the information?

Correct.

Is this only happening only after you call `reset()` function several times? One thing you can do to test if this is the case would be using a new `World` by creating multiple simulations (either by cloning `World` or manually creating multiple `World` with the same configuration) whenever you need to call `reset()` function, and see if this still happens. (Caveat: this would definitely slow down the whole optimization process.)

If it turns out the issues has nothing to do with calling `reset()`, then we might need to narrow down the cause by investigating a minimal executable example that reproduces the same error. This would be very helpful to fix the problem.
