### ISSUE TITLE
Why not use math::expMap() in SE(3) toManifoldPoint()

### ISSUE THREAD

**Issue by qqfly** [dartsim/dart#1255]
Dart implemented the `toManifoldPoint map` of SE(3) space as follows:
[toEuclideanPointImpl< SE3Space >](https://github.com/dartsim/dart/blob/master/dart/math/detail/ConfigurationSpace.hpp#L129)
```
template <>
struct toManifoldPointImpl<SE3Space>
{
  static typename SE3Space::Point run(
      const typename SE3Space::EuclideanPoint& point)
  {
    Eigen::Isometry3d tf(Eigen::Isometry3d::Identity());

    tf.linear() = math::expMapRot(point.head<3>());
    tf.translation() = point.tail<3>();

    return tf;
  }
};
```
Why not use [math::expMap()](https://github.com/dartsim/dart/blob/master/dart/math/Geometry.cpp#L1176) here?

**Comment by jslee02** [comment]
The simple answer would be to match its inverse conversion [`toEuclideanPointImpl<SE3Space>`](toEuclideanPointImpl), which is `(q_ang1, q_lin1) = (log(R), p)`.

I think your real question is why we don't use `(q_ang2, q_lin2) = log(T)` where `T = (R, p)`. The motivation is to keep the linear part of the generalized coordinates intuitive. The angular part are the same as exponential coordinates for rotation (or angle-axis representation) in both conversions when the linear part are different. In the current conversion, it's simply the translation of the SE(3), but `G^-1 p` in `log(T)` (see 3.3.3.2 in this [book](http://hades.mech.northwestern.edu/images/7/7f/MR.pdf)) where G is a function of R. This means that `q_lin2` is not `p` when `R` is not `I`, which is not intuitive to interpret `q_lin2`.

But there is no technical reason not to use other conversions, including log(T), as long as we're consistent in using the conversion because the operations are done in the canonical sapce (i.e., SE(3) for `FreeJoint`).

As a gentle recommendation, we encourage the users to use our new [forum](https://dartsim.discourse.group/) for asking questions. This issue tracker is for reporting bugs. Thanks!
