### ISSUE TITLE
Proposal: Tweak the examples directory to make dart::gui::osg more accessible

### ISSUE THREAD

**Issue by mxgrey** [dartsim/dart#1304]
Many new users will go to the `dart/examples` directory to get started with writing an application, but if they click randomly (which many are likely to do), odds are they'll select one of the old glut-based examples instead of one of the newer osg-based examples.

I would propose changing the directory layout to something like

```
examples
|-- glut_examples_(deprecated)
|   |-- addDeleteSkels
|   |-- atlasSimbicon
|   |-- ...
|-- osg_examples_(recommended)
    |-- osgAtlasPuppet
    |-- osgAtlasSimbicon
    |-- ...
```

We may also want to make sure that all the old glut-based examples have been ported over to osg. If we can put ourselves in a position where people only expect support for OSG instead of both OSG and glut, it might make it easier to address questions.

**Comment by jslee02** [comment]
I like this idea. One thing I'd like to add is changing the name of directories (so the executable names as well). As the intention is to imply the OSG is the recommended renderer, I would remove the `osg` prefix from the OSG examples and add `glut` prefix to GLUT examples. So the structure would be like:
```
examples
|-- glut_examples_deprecated
|   |-- glutAddDeleteSkels
|   |-- glutAtlasSimbicon
|   |-- ...
|-- osg_examples
    |-- atlasPuppet
    |-- atlasSimbicon
    |-- ...
```

Also, I would like to be consistent in the directory name case pattern to be either of all lower cases or Pascal style. I know we've been using Pascal style, but I'm slightly inclined to lower cases since it seems to be more widely used.

**Comment by mxgrey** [comment]
That all sounds good to me!
