### ISSUE TITLE
Close-loop Kinematics Chain Example

### ISSUE THREAD

**Issue by Cfather** [dartsim/dart#1743]
Hi,

I guess someone has mentioned this a long time ago, but does DART support close-loop kinematics chain explicitly? Is there any examples that I can follow, like building a simple 4-bar linkage in DART? 
I can’t find too many tutorials towards building an SDF file describing a close-loop kinematics chain explicitly, and I can’t find any tutorials on how to explicitly construct a close-loop chain using DART’s API. 
I would appreciate it very much if you can help me on that.

Many thanks!

**Comment by jslee02** [comment]
If you want to create a closed-loop kinematic chain in DART, you might find this demo useful. It shows how to construct a closed loop in your code using dynamic joint constraints, since DART's parsers cannot currently parse closed loops:
https://github.com/dartsim/dart/tree/v6.13.0/examples/deprecated_examples/glut_rigid_loop
