### ISSUE TITLE
Are all libs public?

### ISSUE THREAD

**Issue by FrankXie05** [dartsim/dart#1770]
Hi, all
Recently I encountered a problem when using cmake to build `dart`:
After my successful build some extra libs appeared:
![image](https://github.com/dartsim/dart/assets/65999885/3b0535db-4dbb-4d6d-9237-9ae838b776bf)

When I looked at all the examlers, I found that all the examples seemed to only require two libs`dart7-io dart7-gui`.
https://github.com/dartsim/dart/blob/2d3cbdff352b0236b18c85e06f8047a84b3d1098/examples/atlas_puppet/CMakeLists.txt#L7

Question:
Do I need these additional libs? 
https://github.com/dartsim/dart/blob/1fe8fa2c53976d57003edb293b62eac747247d19/dart/CMakeLists.txt#L38-L51

If necessary: Did I turn on those switches and the build was not complete?

If not: What are the minimum libs I need to link against? And which libs are exposed?

BTW, as for third-party lib, I can use vcpkg to solve it. For example, `boost`, `eigen3`, etc. :)

**Comment by jslee02** [comment]
> Do I need these additional libs?

DART consists of the core library, dart, and additional libraries in the form of dart-* where they are built optionally when the required dependencies are detected. The component names for dart7-io and dart7-gui are dart7-io and dart7-gui, respectively. When both dart7-io and dart7-gui are specified, the example requires both components and their dependency components to be built in order to build the example.

> If not: What are the minimum libs I need to link against? And which libs are exposed?

It depends on the example you want. dart would be sufficient for dynamics simulation without any IO and visualization, but more libraries may be needed for additional features. Please refer to the examples to get a better sense of what is required.
