### ISSUE TITLE
Build error with libbullet

### ISSUE THREAD

**Issue by olzhas** [dartsim/dart#418]
Hello everyone,
today I updated dart to 5.0.0, then built it and tried to rebuild my project. I failed to do obtaining this error:

/usr/local/include/dart/collision/bullet/BulletTypes.h:50: error: 'btInfinityMask' was not declared in this scopec
   return btInfinityMask;
          ^

The problem can be fixed removing the line BulletTypes.h:50.

I use libbullet 2.81 on ubuntu 14.04.2 x86_64.

**Comment by jslee02** [comment]
The dummy function was added to suppress unused-variable-warnings due to btInfinityMask but it doesn't seem to be exposed on all the platforms. Actually [bitInfinityMask is surrounded by some preprocessors](https://github.com/bulletphysics/bullet3/blob/master/src/LinearMath/btScalar.h#L364), and Bullet 2.83 added [similar code](https://github.com/bulletphysics/bullet3/blob/master/src/LinearMath/btScalar.h#L366) only when the variable is exposed.

I don't know how to expose the dummy function only when bitInfinityMask is exposed. Maybe we should remove the dummy function and let the compiler to complains warnings.

**Comment by jslee02** [comment]
This should be fixed by #480. Please confirm.

**Comment by jslee02** [comment]
Closing for now. Please reopen if it sill doesn't work.
