### ISSUE TITLE
DART will wrongly prompt warning for setting initial joint positions out of range

### ISSUE THREAD

**Issue by jyf588** [dartsim/dart#869]
Hello everyone,

I had this joint in my Skel file:

>             <joint type="prismatic" name="j_gripper2">
>                 <parent>forearm</parent>
>                 <child>gripper2</child>
>                 <axis>
>                     <xyz>0.0 0.0 -1.0</xyz>
>                     <limit>
>                         <lower>0.01</lower>
>                         <upper>0.10</upper>
>                     </limit> 
>                 </axis>
>                 <init_pos>0.03</init_pos>
>             </joint>

When I ran the simulation, DART gave me the following warning: 

>[1;33mWarning [GenericJoint.hpp:1289][0m [GenericJoint::setRestPosition] Value of _q0 [0], is out of the limit range [0.01, 0.1] for index [0] of Joint [Joint].

Actually I can see from my window that the init_pos is indeed correctly set to 0.03 instead of 0.0. I don't know why in function GenericJoint::setRestPosition(), it will think my init_pos is 0.0

Thanks,
Yifeng

**Comment by mxgrey** [comment]
The rest position refers to the "zero spring potential" position that gets used when computing spring stiffness. The default value for this is zero.

Admittedly, this warning might be overly cautious, since many users probably don't even use the spring stiffness. Also, it's plausible that there are situations where the rest position is desired to be outside the position limits. We could consider removing this warning.

**Comment by jyf588** [comment]
I see... The warning refers to the unspecified <spring_rest_position>, which has default 0 value. It has nothing to do with my <init_pos> value.

**Comment by mxgrey** [comment]
Exactly. I'm glad you brought this up, though, because I think it's worthwhile to consider removing this warning.
